import Head from "next/head";
import ContactUs from "./components/contactUs";
import NavbarIndex from "./components/navbarIndex";
import Outro from "./components/outro";
import Image from "next/image";
import Salamun from "../public/logo_salamun.png";
import Webdev from "../public/i24.png";
import Server from "../public/i23.png";
import Desktop from "../public/i22.png";
import Mobile from "../public/i26.png";
import Team from "../public/kangFaerul.png";
import Linkedin from "../public/icon/ico-linkedin.svg";
import Github from "../public/icon/ico-github.svg";
import Youtube from "../public/icon/ico-youtube.svg";
import Php from "../public/tech/26.png";
import Node from "../public/tech/27.png";
import Go from "../public/tech/28.png";
import Reactjs from "../public/tech/29.png";
import Vue from "../public/tech/29.png";
import MongoDB from "../public/tech/33.png";
import Db from "../public/tech/34.png";
import Kotlin from "../public/tech/35.png";
import Swift from "../public/tech/36.png";
import Mysql from "../public/tech/31.png";
import Elephant from "../public/tech/32.png";
import Web3 from "../public/tech/37.png";
import Aws from "../public/tech/38.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>PT Salamun Teknologi Indonesia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        <link
          href="https://fonts.googleapis.com/css2?family=Mulish&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      <main>
        {/* Navbar */}
        <NavbarIndex />
        {/* Tutup Navbar */}

        {/* Intro */}
        <section id="intro" className="mt-[125px] md:mt-[183px] mx-auto">
          <div>
            <h1 className="ml-8 text-xl tracking-wider md:text-3xl md:tracking-wide md:ml-10 md:mt-[-25px] md:ml-28 lg:ml-[139px] md:tracking-widest lg:mt-0 lg:leading-[50px] lg:text-4xl font-semibold">
              A Software House <br />
              Specializing in Application <br />
              Development
            </h1>
            <div className=" flex">
              <ContactUs />
            </div>
          </div>
        </section>
        {/* Tutup Intro */}

        {/* Service */}
        <section id="service">
          <h1 className=" text-3xl pt-[8rem] text-blue-300 text-center">
            What We Do?
          </h1>
          <p className=" text-gray-50 pt-3 text-center">
            The service we offer is specifically <br /> designed to meet your
            <br />
            requirements.
          </p>
          <div className="bg-transparent grid grid-rows-4 md:grid-rows-4 lg:grid-rows-4 xl:grid-rows-2 mt-28 grid-flow-col">
            <div className="bg-transparent overflow-hidden mx-auto md:mx-auto lg:mx-auto xl:ml-36 text-gray-50 xl:mt-[-4rem]">
              <Image
                className=" mb-[-5rem] w-24 ml-10 md:w-48 md:ml-[5rem] md:mb-[-6rem]"
                src={Webdev}
                alt="webdev"
              />
              <div className=" shadow2 px-3 py-2 m-12 w-[212px] mb-[14px] mr-2 md:px-6 md:py-4 bg-biru md:ml-24 md:w-[424px] md:mb-7 md:mr-4 rounded-2xl">
                <div className=" mt-8 pl-8 md:mt-24 md:pl-16">
                  <div className="text-xl text-blue-300 mb-2">
                    Web Development
                  </div>
                  <p className="text-xs md:text-base">
                    We help you to Develop application for your business, both
                    vertical (industry specific) and horizontal (serve a
                    particular need across all organizations and industries).
                  </p>
                </div>
              </div>
            </div>
            <div className="bg-transparent overflow-hidden mx-auto md:mx-auto lg:mx-auto xl:ml-36 text-gray-50 xl:mt-[-4rem]">
              <Image
                className="mb-[-5rem] w-24 ml-10 md:mb-[-6rem] md:w-48 md:ml-[5rem]"
                src={Server}
                alt="webdev"
              />
              <div className=" shadow2 px-3 py-2 m-12 w-[212px] mb-[14px] mr-2 md:px-6 md:py-4 bg-biru md:ml-24 md:w-[424px] md:mb-7 md:mr-4 rounded-2xl">
                <div className="mt-8 pl-8 md:mt-24 md:pl-16">
                  <div className="text-xl text-blue-300 mb-2">
                    Managed Server
                  </div>
                  <p className="text-xs md:text-base">
                    We can manage your domain and application servers from
                    registration, renewal, configuration settings and other
                    related matters including integrating software into
                    business.
                  </p>
                </div>
              </div>
            </div>
            <div className="bg-transparent overflow-hidden mx-auto md:mx-auto lg:mx-auto xl:mr-36 text-gray-50 xl:mt-[-4rem] xl:mt-24">
              <Image
                className="mb-[-5rem] w-24 ml-10 md:mb-[-6rem] md:w-48 md:ml-[5rem]"
                src={Desktop}
                alt="webdev"
              />
              <div className=" shadow2 px-3 py-2 m-12 w-[212px] mb-[14px] mr-2 md:px-6 md:py-4 bg-biru md:ml-24 md:w-[424px] md:mb-7 md:mr-4 rounded-2xl">
                <div className=" mt-8 pl-8 md:mt-24 md:pl-16">
                  <div className="text-xl text-blue-300 mb-2">
                    Desktop Development
                  </div>
                  <p className="text-xs md:text-base">
                    Is there a technology-based product that you want to
                    develop? Trust us to develop it with an end-to-end solution
                    from the design process to its implementation.
                  </p>
                </div>
              </div>
            </div>
            <div className="bg-transparent overflow-hidden mx-auto md:mx-auto lg:mx-auto xl:mr-36 text-gray-50 xl:mt-[-4rem] xl:mt-24">
              <Image
                className="mb-[-5rem] w-24 ml-10 md:mb-[-6rem] md:w-48 md:ml-[5rem]"
                src={Mobile}
                alt="webdev"
              />
              <div className=" shadow2 px-3 py-2 m-12 w-[212px] mb-[14px] mr-2 md:px-6 md:py-4 bg-biru md:ml-24 md:w-[424px] md:mb-7 md:mr-4 rounded-2xl">
                <div className="mt-8 pl-8 md:mt-24 md:pl-16">
                  <div className="text-xl text-blue-300 mb-2">
                    Mobile App Development
                  </div>
                  <p className="text-xs md:text-base">
                    In today's market, every company needs an effective website.
                    Likewise with mobile-based applications that will help
                    improve your company's image.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        {/* Tutup Service */}

        {/* Teams */}
        <section>
          <div id="teams">
            <div className="text-center">
              <h1 className="md:text-3xl text-sm pt-[8rem] font-semibold text-blue-300">
                We Are Proud of Our Team
              </h1>
              <br />
              <p className="text-sm md:text-base text-gray-600 font-semibold">
                Just sit back and relax while we take care of <br /> your
                business needs for you.
              </p>
              <br />
              <br />

              <div className=" xl:mx-52 md:mx-24">
                <div className="grid xl:grid-cols-4 lg:grid-cols-4 md:grid-cols-4 grid-cols-2 gap-0 flex justify-items-center">
                  <div className="w-[106px] h-[165px] lg:w-[200px] lg:h-[330px] rounded overflow-hidden shadow3">
                    <Image
                      className=" w-[87px] lg:w-[164px] mx-auto my-[6px] lg:my-3"
                      src={Team}
                      alt="Sunset in the mountains"
                    />
                    <div className="px-1 py-1 lg:px-6 lg:py-4">
                      <div className="font-bold text-[12px] lg:text-xl lg:mb-2">
                        Faerul Salamun
                      </div>
                      <h1 className="text-gray-400 text-sm font-semibold lg:text-base">
                        CEO
                      </h1>
                      <div className="px-5 pt-1 lg:px-6 lg:pt-3 gap-x-2 flex pb-2">
                        <a href="">
                          <Image
                            className="w-[15px] md:w-[30px]"
                            src={Linkedin}
                            alt=""
                          />
                        </a>
                        <a href="" className="w-[15px] md:w-[30px]">
                          <Image src={Github} alt="" />
                        </a>
                        <a href="" className="w-[15px] md:w-[30px]">
                          <Image src={Youtube} alt="" />
                        </a>
                      </div>
                    </div>
                  </div>
                  <div className="w-[106px] h-[165px] lg:w-[200px] lg:h-[330px] rounded overflow-hidden shadow3">
                    <Image
                      className=" w-[87px] lg:w-[164px] mx-auto my-[6px] lg:my-3"
                      src={Team}
                      alt=""
                    />
                    <div className="px-1 py-1 lg:px-6 lg:py-4">
                      <div className="font-bold text-[12px] lg:text-xl lg:mb-2">
                        Faerul Salamun
                      </div>
                      <h1 className="text-gray-400 text-sm font-semibold lg:text-base">
                        CEO
                      </h1>
                      <div className="px-5 pt-1 lg:px-6 lg:pt-3 gap-x-2 flex pb-2">
                        <a href="">
                          <Image
                            className="w-[15px] md:w-[30px]"
                            src={Linkedin}
                            alt=""
                          />
                        </a>
                        <a href="" className="w-[15px] md:w-[30px]">
                          <Image src={Github} alt="" />
                        </a>
                        <a href="" className="w-[15px] md:w-[30px]">
                          <Image src={Youtube} alt="" />
                        </a>
                      </div>
                    </div>
                  </div>
                  <div className="w-[106px] h-[165px] lg:w-[200px] lg:h-[330px] mt-8 md:mt-0 rounded overflow-hidden shadow3">
                    <Image
                      className=" w-[87px] lg:w-[164px] mx-auto my-[6px] lg:my-3"
                      src={Team}
                      alt="Sunset in the mountains"
                    />
                    <div className="px-1 py-1 lg:px-6 lg:py-4">
                      <div className="font-bold text-[12px] lg:text-xl lg:mb-2">
                        Faerul Salamun
                      </div>
                      <h1 className="text-gray-400 text-sm font-semibold lg:text-base">
                        CEO
                      </h1>
                      <div className="px-5 pt-1 lg:px-6 lg:pt-3 gap-x-2 flex pb-2">
                        <a href="">
                          <Image
                            className="w-[15px] md:w-[30px]"
                            src={Linkedin}
                            alt=""
                          />
                        </a>
                        <a href="" className="w-[15px] md:w-[30px]">
                          <Image src={Github} alt="" />
                        </a>
                        <a href="" className="w-[15px] md:w-[30px]">
                          <Image src={Youtube} alt="" />
                        </a>
                      </div>
                    </div>
                  </div>
                  <div className="w-[106px] h-[165px] lg:w-[200px] lg:h-[330px] mt-8 md:mt-0 rounded overflow-hidden shadow3">
                    <Image
                      className=" w-[87px] lg:w-[164px] mx-auto my-[6px] lg:my-3"
                      src={Team}
                      alt="Sunset in the mountains"
                    />
                    <div className="px-1 py-1 lg:px-6 lg:py-4">
                      <div className="font-bold text-[12px] lg:text-xl lg:mb-2">
                        Faerul Salamun
                      </div>
                      <h1 className="text-gray-400 text-sm font-semibold lg:text-base">
                        CEO
                      </h1>
                      <div className="px-5 pt-1 lg:px-6 lg:pt-3 gap-x-2 flex pb-2">
                        <a href="">
                          <Image
                            className="w-[15px] md:w-[30px]"
                            src={Linkedin}
                            alt=""
                          />
                        </a>
                        <a href="" className="w-[15px] md:w-[30px]">
                          <Image src={Github} alt="" />
                        </a>
                        <a href="" className="w-[15px] md:w-[30px]">
                          <Image src={Youtube} alt="" />
                        </a>
                      </div>
                    </div>
                  </div>

                  <br />
                  <br />
                  <br />
                </div>
              </div>
            </div>
          </div>
        </section>
        {/* Tutup Teams */}

        {/* Tech */}
        <section>
          <div id="techstack">
            <h1 className=" uppercase text-center text-sm md:text-xl lg:text-3xl mb-6 pt-[8rem] font-bold text-blue-300">
              Tech Stack
            </h1>
            <div className="grid grid-flow-col auto-cols-max items-center justify-center gap-x-[11px]">
              <div>
                <Image
                  className="w-[63px] md:w-[103px] lg:w-full h-auto"
                  src={Php}
                  alt=""
                />
              </div>
              <div>
                <Image
                  className="w-[63px] md:w-[103px] lg:w-full h-auto"
                  src={Node}
                  alt=""
                />
              </div>
              <div>
                <Image
                  className="w-[50px] md:w-[90px] lg:w-full h-auto"
                  src={Go}
                  alt=""
                />
              </div>
              <div>
                <Image
                  className="w-[35px] md:w-[75px] lg:w-full h-auto"
                  src={Reactjs}
                  alt=""
                />
              </div>
              <div>
                <Image
                  className="w-[22px] md:w-[62px] lg:w-full h-auto"
                  src={Vue}
                  alt=""
                />
              </div>
            </div>
            <div className="grid grid-flow-col auto-cols-max items-center justify-center gap-x-[11px] md:gap-x-11">
              <div>
                <Image
                  className="w-[63px] md:w-[103px] lg:w-full h-auto"
                  src={MongoDB}
                  alt=""
                />
              </div>
              <div>
                <Image
                  className="w-[32px] md:w-[52px] lg:w-full h-auto"
                  src={Db}
                  alt=""
                />
              </div>
              <div>
                <Image
                  className="w-[62px] md:w-[82px] lg:w-full h-auto"
                  src={Kotlin}
                  alt=""
                />
              </div>
              <div>
                <Image
                  className="w-[62px] md:w-[82px] lg:w-full h-auto"
                  src={Swift}
                  alt=""
                />
              </div>
            </div>
            <div className="grid grid-flow-col auto-cols-max items-center justify-center gap-x-[4px] md:gap-x-10">
              <div>
                <Image
                  className="w-[62px] md:w-[82px] lg:w-full h-auto"
                  src={Mysql}
                  alt=""
                />
              </div>
              <div>
                <Image
                  className="w-[62px] md:w-[82px] lg:w-full h-auto"
                  src={Elephant}
                  alt=""
                />
              </div>
              <div>
                <Image
                  className="w-[63px] md:w-[83px] lg:w-full h-auto"
                  src={Web3}
                  alt=""
                />
              </div>
              <div>
                <Image
                  className="w-[38px] lg:w-full h-auto ml-7"
                  src={Aws}
                  alt=""
                />
              </div>
            </div>
          </div>
        </section>
        {/* Tutup Tech */}

        {/* Maps */}
        <section className="mt-28 ">
          <div className="pt-[13px] pb-[13px] px-[10px] md:px-9 md:pt-[19px] lg:pt-10 lg:pb-10 lg:px-10 shadow3 lg:w-[861px] mx-auto">
            <div className="w-auto h-auto mx-auto md:w-[700px] md:h-[330px]">
              <iframe
                className="w-auto h-auto md:h-[328px] md:w-[678px] mx-auto"
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3960.498424594971!2d107.64474461546196!3d-6.95038076997705!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e68dd950cc15259%3A0xf5a14138db1906d6!2sPT%20Salamun%20Teknologi%20Indonesia!5e0!3m2!1sid!2sid!4v1664611387561!5m2!1sid!2sid"
              ></iframe>
            </div>
          </div>
          <br />
          <br />
          <br />
          <br />
          <br />
        </section>
        {/* Tutup Maps */}

        {/* Outro */}
        <Outro />
        {/* Tutup Outro */}

        {/* Footer */}
        <footer className="text-center text-white lg:text-left bg-blue-600 mt-[87px]">
          <div className="mx-6 py-10 text-center md:text-left">
            <div className="grid grid-1 md:grid-cols-2 lg:grid-cols-2 mx-auto gap-8">
              <div className="">
                <div className="bg-white rounded-full w-full lg:w-[450px] mx-auto mb-4 flex items-center justify-center md:justify-start">
                  <Image className="mx-auto" src={Salamun} alt="" />
                </div>
                <p className=" text-center">
                  We are IT Solutions company from Bandung, Indonesia. We
                  design, create, and develop a variety of software and in all
                  matters relating to the application of Information and
                  Communication Technology.
                </p>
              </div>

              <div className="">
                <h6 className="uppercase font-semibold mb-4 flex justify-center md:justify-start">
                  Contact
                </h6>
                <p className="flex items-center justify-center md:justify-start mb-4">
                  <svg
                    aria-hidden="true"
                    focusable="false"
                    data-prefix="fas"
                    data-icon="home"
                    className="w-4 mr-4"
                    role="img"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 576 512"
                  >
                    <path
                      fill="currentColor"
                      d="M280.37 148.26L96 300.11V464a16 16 0 0 0 16 16l112.06-.29a16 16 0 0 0 15.92-16V368a16 16 0 0 1 16-16h64a16 16 0 0 1 16 16v95.64a16 16 0 0 0 16 16.05L464 480a16 16 0 0 0 16-16V300L295.67 148.26a12.19 12.19 0 0 0-15.3 0zM571.6 251.47L488 182.56V44.05a12 12 0 0 0-12-12h-56a12 12 0 0 0-12 12v72.61L318.47 43a48 48 0 0 0-61 0L4.34 251.47a12 12 0 0 0-1.6 16.9l25.5 31A12 12 0 0 0 45.15 301l235.22-193.74a12.19 12.19 0 0 1 15.3 0L530.9 301a12 12 0 0 0 16.9-1.6l25.5-31a12 12 0 0 0-1.7-16.93z"
                    ></path>
                  </svg>
                  <p className="">
                    Jl. Kiara Sari Permai XI No. 34, Buahbatu, Kota Bandung,
                    Jawa Barat, Indonesia
                  </p>
                </p>
                <p className="flex items-center justify-center md:justify-start mb-4">
                  <svg
                    aria-hidden="true"
                    focusable="false"
                    data-prefix="fas"
                    data-icon="envelope"
                    className="w-4 mr-4"
                    role="img"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 512 512"
                  >
                    <path
                      fill="currentColor"
                      d="M502.3 190.8c3.9-3.1 9.7-.2 9.7 4.7V400c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V195.6c0-5 5.7-7.8 9.7-4.7 22.4 17.4 52.1 39.5 154.1 113.6 21.1 15.4 56.7 47.8 92.2 47.6 35.7.3 72-32.8 92.3-47.6 102-74.1 131.6-96.3 154-113.7zM256 320c23.2.4 56.6-29.2 73.4-41.4 132.7-96.3 142.8-104.7 173.4-128.7 5.8-4.5 9.2-11.5 9.2-18.9v-19c0-26.5-21.5-48-48-48H48C21.5 64 0 85.5 0 112v19c0 7.4 3.4 14.3 9.2 18.9 30.6 23.9 40.7 32.4 173.4 128.7 16.8 12.2 50.2 41.8 73.4 41.4z"
                    ></path>
                  </svg>
                  support@salamunteknologi.com
                </p>
                <p className="flex items-center justify-center md:justify-start mb-4">
                  <svg
                    aria-hidden="true"
                    focusable="false"
                    data-prefix="fas"
                    data-icon="phone"
                    className="w-4 mr-4"
                    role="img"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 512 512"
                  >
                    <path
                      fill="currentColor"
                      d="M493.4 24.6l-104-24c-11.3-2.6-22.9 3.3-27.5 13.9l-48 112c-4.2 9.8-1.4 21.3 6.9 28l60.6 49.6c-36 76.7-98.9 140.5-177.2 177.2l-49.6-60.6c-6.8-8.3-18.2-11.1-28-6.9l-112 48C3.9 366.5-2 378.1.6 389.4l24 104C27.1 504.2 36.7 512 48 512c256.1 0 464-207.5 464-464 0-11.2-7.7-20.9-18.6-23.4z"
                    ></path>
                  </svg>
                  <p>
                    +62 22 87307674 (Calls Only) <br />
                    +62 813 202 916 40 (Calls & WA)
                  </p>
                </p>
              </div>
            </div>
          </div>
        </footer>
        {/* Tutup Footer */}
      </main>
    </>
  );
}
